# -*- coding: utf-8 -*-
# """Project_PartB.ipynb
# 
# Automatically generated by Colab.
# 
# Original file is located at
#     https://colab.research.google.com/drive/12KlGZj5gZYvzSXJjYV9bthBduQqBpgiu
# 
# # Part B
# Use a real-world cross-section data set with a continuous dependent variable (Y), and at least
# 4 independent variables, with at least one being continuous (X1, X2, ..) . Consider the sample
# size to be 120 or more.
# """

# Install packages if not installed
# dplyr: Data manipulation
# stargazer: Regression tables for reporting
# ggplot2: Data visualization
# lmtest: Breusch–Pagan test and other diagnostic tests
# performance: Multicollinearity checks and model diagnostics

packages <- c("dplyr", "stargazer", "ggplot2", "lmtest", "performance")

for (pkg in packages) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg)
    library(pkg, character.only = TRUE)
  }
}

# Read data
DATA_URL <- "https://raw.githubusercontent.com/eren-darici/ECON6190/refs/heads/main/data/medical_insurance.csv"
data <- read.csv(DATA_URL)
head(data, 5)

# Check missing values
any(is.na(data))

# Select Y (dependent variable)
y <- data$annual_medical_cost

# Select X (6 independent variables)
X <- data[, c("age",
            "bmi",
            "chronic_count",
            "visits_last_year",
            "medication_count",
              "hospitalizations_last_3yrs")]

# Assertion to check missing
stopifnot(nrow(X) == length(y))

# Combine data
model_data <- data.frame(X, y = y)

# """# Part B.i.
# Provide descriptive statistics for all variables including their variances. Run OLS
# regression of Y on all X variables and report the results in a Table. Comment on
# statistical significance of regression coefficients at 10%, 5% and 1% levels? How is
# the overall in-sample fit of the model? Justify.
# """

# Descriptive statistics
describe_func <- function(x) {
  round(c(
    mean = mean(x, na.rm = TRUE),
    sd = sd(x, na.rm = TRUE),
    variance = var(x, na.rm = TRUE),
    min = min(x, na.rm = TRUE),
    q25 = quantile(x, 0.25, na.rm = TRUE),
    median = median(x, na.rm = TRUE),
    q75 = quantile(x, 0.75, na.rm = TRUE),
    max = max(x, na.rm = TRUE)
  ), 4)
}

# Appply function to model data
descriptive_stats <- sapply(model_data, describe_func)
descriptive_stats

# Run OLS
model <- lm(y ~ ., data=model_data)
summary(model)

# Stargazer for better table
stargazer(model, type = "text", title = "OLS Regression Results", report = "vsp*", digits = 6)
# Latex
#stargazer(model, type = "latex", title = "OLS Regression Results", report = "vsp*", digits = 6)

# """# Part B.ii.
# Generate in-sample predictions and compare it to observed Y. [You may use kernel
# density plots for a quick comparison. Provide a brief comment].
# """

# Generate in sample predictions
pred <- predict(model)

# Bind data
data_kde <- data.frame(
  value = c(y, pred),
  type = rep(c("Observed", "Predicted"), c(length(y), length(pred)))
)

# Plot KDE
ggplot(data_kde, aes(x=value, fill=type)) +
  geom_density(alpha=0.4) +
  labs(
    x = "Annual Medical Cost",
    y = "Density"
  )

# """# Part B.iii.
# Run a heteroscedasticity test and report your result with conclusion
# """

# Run BP Test
bp_test <- bptest(model)
bp_test

# """# Part B.iv.
# Run a multicollinearity test and report your result with conclusion.
# """

# Test VIF (Variance Inflation Factor)
vif_values <- check_collinearity(model)
vif_values

# """# Part B.v.
# Drop any 2 independent variables of your choice and run an F-test to explain whether
# you should prefer the restricted (0-type restriction as explained in class) or the
# unrestricted model. Make sure to report your F-test results
# """

# Drop visits_last_year, medication_count
restricted_model_data <- model_data %>%
  select(-visits_last_year, -medication_count)

restricted_model_data

# Run OLS on restricted model
restricted_model <- lm(y ~ ., data=restricted_model_data)
stargazer(restricted_model, type = "text", title = "OLS Regression Results", report = "vsp*", digits = 6)
# Latex
#stargazer(restricted_model, type = "latex", title = "OLS Regression Results", report = "vsp*", digits = 6)

# F-Test
f_test <- anova(restricted_model, model)
stargazer(as.data.frame(f_test), type = "text", title = "OLS Regression Results", digits = 6)
#stargazer(as.data.frame(f_test), type = "latex", title = "OLS Regression Results", digits = 6)

